// Deliberately NOT '../api/client'. That shared instance responds to any 401 by
// calling TokenStorage.clearAll(), so a single expired token turned one failed
// chat request into a full logout — every later call then went out with no
// Authorization header at all and the assistant stayed permanently unreachable.
//
// This client (despite living under worker/) is the only one in the app that
// refreshes the token on 401 and retries, and it reads the same storage keys and
// base URL, so it is correct for all four roles.
import apiClient from '../worker/api/client';
import { API_BASE_URL } from '../worker/constants/config';
import { TokenStorage } from '../worker/utils/storage';

/**
 * Role-aware HSE assistant.
 *
 * There is deliberately no role parameter here. The backend derives both the
 * data snapshot and the assistant's persona from the JWT (see
 * `backend/app/controllers/ai.py:_role_bucket`), so a worker's client cannot
 * request a manager-scoped answer by asking for one.
 */

export type AiRole = 'user' | 'assistant';

export interface AiMessage {
  role: AiRole;
  content: string;
}

export interface AiReply {
  answer: string;
  /** Model that served the reply, or 'fallback' when no provider is configured. */
  model: string;
  /** Which role profile the backend applied: worker | supervisor | manager | auditor. */
  scope?: string;
}

/**
 * A single LLM round-trip regularly runs past the 15s default on the shared
 * client — the backend assembles a live DB snapshot and then waits on the model.
 * Anything under ~45s produces spurious timeouts on a slow connection.
 */
const AI_TIMEOUT_MS = 60000;

export async function sendAiMessage(
  userMessage: string,
  history: AiMessage[] = [],
): Promise<AiReply> {
  const messages: AiMessage[] = [...history, { role: 'user', content: userMessage }];

  const res = await apiClient.post(
    '/ai/chat',
    { messages },
    { timeout: AI_TIMEOUT_MS },
  );

  // `/ai/chat` returns a bare object, so the client's {success,data} unwrap
  // interceptor passes it through untouched.
  const body = res.data ?? {};
  const answer =
    typeof body.answer === 'string' && body.answer.trim().length > 0
      ? body.answer
      : 'No response generated by the AI service.';

  return { answer, model: body.model ?? 'unknown', scope: body.scope };
}

/**
 * Streaming counterpart to sendAiMessage — calls `/ai/chat/stream` and invokes
 * `onDelta` as text arrives, so the first words appear in ~1-2s instead of the
 * user staring at a spinner for the whole 5-15s generation.
 *
 * Deliberately XMLHttpRequest and not fetch: React Native's fetch is a polyfill
 * over XHR and never populates `response.body`, so `.getReader()` — the way the
 * web client consumes this same endpoint — does not exist here. XHR does deliver
 * `responseText` incrementally, but only once a progress listener is attached,
 * which is why `onprogress` is set even though `pump()` reads no event payload.
 *
 * Resolves with the full reply. Rejects on transport/auth failure so the caller
 * can fall back to sendAiMessage, which goes through apiClient and therefore
 * still gets the 401 refresh-and-retry this raw request cannot do for itself.
 */
export function streamAiMessage(
  userMessage: string,
  history: AiMessage[] = [],
  onDelta?: (chunk: string, fullSoFar: string) => void,
): Promise<AiReply> {
  const messages: AiMessage[] = [...history, { role: 'user', content: userMessage }];

  return new Promise<AiReply>(async (resolve, reject) => {
    let token: string | null = null;
    try {
      token = await TokenStorage.getAccessToken();
    } catch {
      // Fall through with no token; the backend will 401 and we reject below.
    }

    const xhr = new XMLHttpRequest();
    xhr.open('POST', `${API_BASE_URL}/ai/chat/stream`);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.setRequestHeader('Accept', 'text/event-stream');
    if (token) xhr.setRequestHeader('Authorization', `Bearer ${token}`);
    xhr.timeout = AI_TIMEOUT_MS;

    let full = '';
    let model = 'unknown';
    let scope: string | undefined;
    // How much of the accumulating responseText we have already turned into
    // frames, plus any trailing partial frame not yet terminated by a blank line.
    let consumed = 0;
    let partial = '';

    const handleFrame = (frame: string) => {
      const line = frame.split('\n').find((l) => l.startsWith('data:'));
      if (!line) return;
      let payload: any;
      try {
        payload = JSON.parse(line.slice('data:'.length).trim());
      } catch {
        return; // malformed frame — skip rather than kill the stream
      }
      if (typeof payload.delta === 'string') {
        full += payload.delta;
        onDelta?.(payload.delta, full);
      }
      if (payload.done) {
        if (typeof payload.model === 'string') model = payload.model;
        if (typeof payload.scope === 'string') scope = payload.scope;
      }
    };

    const pump = () => {
      const text = xhr.responseText || '';
      if (text.length <= consumed) return;
      partial += text.slice(consumed);
      consumed = text.length;
      const frames = partial.split('\n\n');
      partial = frames.pop() ?? '';
      frames.forEach(handleFrame);
    };

    xhr.onprogress = pump;

    xhr.onload = () => {
      pump();
      if (partial.trim()) handleFrame(partial); // final frame without trailing blank line
      if (xhr.status < 200 || xhr.status >= 300) {
        reject({ response: { status: xhr.status } });
        return;
      }
      resolve({ answer: full, model, scope });
    };

    xhr.onerror = () => reject({ message: 'network error' });
    xhr.ontimeout = () => reject({ code: 'ECONNABORTED' });

    xhr.send(JSON.stringify({ messages }));
  });
}

/**
 * What the chat screens actually call: stream when possible, fall back to the
 * blocking endpoint when the stream cannot be established.
 *
 * The fallback only fires when nothing was rendered yet. Once deltas have
 * reached the screen, re-asking would splice a second, differently-worded answer
 * onto the partial text the user is already reading — the same reason the
 * backend stops rather than switching providers mid-stream.
 */
export async function askAi(
  userMessage: string,
  history: AiMessage[] = [],
  onDelta?: (chunk: string, fullSoFar: string) => void,
): Promise<AiReply> {
  let received = false;
  try {
    return await streamAiMessage(userMessage, history, (chunk, sofar) => {
      received = true;
      onDelta?.(chunk, sofar);
    });
  } catch (err) {
    if (received) throw err;
    return sendAiMessage(userMessage, history);
  }
}

export interface AskDataReply {
  answer: string;
  /** The SELECT(s) that produced the answer — read-only and scoped to the caller's org. */
  sql: string[];
  model?: string;
}

/**
 * Ask a question that must be answered from the database rather than from the
 * role briefing — "how many incidents last month", "which site has the most
 * overdue CAPAs". Claude writes a SELECT, the backend validates and runs it,
 * then phrases the result.
 *
 * Deliberately not streamed: nothing exists to stream until the query has run,
 * so a stream would show a spinner and then the whole answer at once anyway.
 * Uses the same generous timeout as chat — this makes two model round-trips.
 */
export async function askData(question: string): Promise<AskDataReply> {
  const res = await apiClient.post(
    '/ai/ask-data',
    { question },
    { timeout: AI_TIMEOUT_MS },
  );
  // `/ai/ask-data` returns a bare object, so the client's {success,data} unwrap
  // interceptor passes it through — read res.data.answer, not res.data.data.
  const body = res.data ?? {};
  return {
    answer:
      typeof body.answer === 'string' && body.answer.trim().length > 0
        ? body.answer
        : 'No answer generated for that question.',
    sql: Array.isArray(body.sql) ? body.sql : [],
    model: body.model,
  };
}

/**
 * Turn a failed chat request into something the user can act on.
 *
 * "Couldn't reach the assistant" was shown for every failure, including an
 * expired session — which sent people looking at their connection when the real
 * fix was signing in again.
 */
export function aiErrorText(err: any): string {
  if (err?.code === 'ECONNABORTED') {
    return 'That took too long to answer. Check your connection and try again.';
  }
  const status = err?.response?.status;
  if (status === 401) {
    return 'Your session has expired. Please sign out and sign in again.';
  }
  if (status && status >= 500) {
    return 'The assistant is having trouble on the server side. Please try again shortly.';
  }
  return "I couldn't reach the assistant just now. Please try again in a moment.";
}

/** Reports which provider the backend has configured — handy for a settings screen. */
export async function getAiStatus(): Promise<Record<string, unknown>> {
  const res = await apiClient.get('/ai/status');
  return res.data ?? {};
}
